### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by zhangchen91** [siva17/JSBridge#1]
in the demo，the index.html doesn't include the JSBridge.js

it doesn't matter?

**Comment by siva17** [comment]
Hi
The beauty of this tiny framework is, don't need to include JSBridge.js in the html file.
JSBridge.js will be injected on to HTML by native code (iOS/Android), when it's DOM is loaded. So  you cannot use the JSBridge APIs during application boot up.

Coming to "how to use". I need some time to update detailed documentation.

I have similar project MyJSWebView which has only API Capability and detailed documentation. It has some limitations and so I created this JSBridge.
https://github.com/siva17/MyJSWebView

Thanks
Siva
