### ISSUE TITLE
hi, some problems about the android JSBridge

### ISSUE THREAD

**Issue by fansding** [siva17/JSBridge#2]
I run the demo, the native can send message to the webview, but can not receive the message from the webview. 
I don't know if this is a known issues, the handler just doesn't work.
hope you can help me.

**Comment by siva17** [comment]
Placed a buttons on WebView to send message from WebView to Native. Can you tell me which button is not working.
In fact you can see the message log on the HTML page. Also you can see the activity in eclipse logcat for seeing the logs on native side.
Please note all the buttons are not supported on Native and you should be message with "UN-SUPPORTED API/EVENT" from Native if it is not supported.

As of now, in Android, I tested for Android 5.0. I think there are some issue below Android 5.0. Will fix the same as soon as possible. Mean time, if you know the issue, please let me know.

Thanks
Siva

**Comment by siva17** [comment]
Hi Fansding
Did you get what is the issue? I am still working on this project and will post more documentation in near future. For now, I am closing this. If you want, you can reopen or open a new issue.

Thanks
Siva
